name = "forum-egress"
main = "worker.js"
compatibility_date = "2024-04-19"

kv_namespaces = [
  { binding = "FORUM_REPORTS", id = "f120d14428794dc490ade0b03db299b1" }
]

routes = [
  { pattern = "forum-egress.yourcommunity.forum", custom_domain = true }
]
